version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.18.0-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-
      - run: yarn
      - run: sudo apt-get install chromium
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - run: yarn screenshot
      - run:
          name: Set up environment variables
          command: |
            echo $GCP_CREDENTIALS > ./google_application_credentials.json
            echo 'export GOOGLE_APPLICATION_CREDENTIALS=./google_application_credentials.json' >> $BASH_ENV
            source $BASH_ENV
      - run: yarn visual-testing
