version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.8
jobs:
  build:
    docker:
      - image: cimg/node:18.18.0-browsers
    working_directory: ~/repo
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-
      - run: yarn --ignore-engines
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - run: yarn screenshot
      - run:
          name: Set up environment variables
          command: |
            echo $GCP_CREDENTIALS > ./google_application_credentials.json
            echo 'export GOOGLE_APPLICATION_CREDENTIALS=./google_application_credentials.json' >> $BASH_ENV
            source $BASH_ENV
      - run: yarn visual-testing
